name: Benchmarks (Comment)

# NOTE: Workflow disabled - see issue for details on fixes needed
# To re-enable, remove the `if: false` from the job below
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows:
      - Benchmarks
    types:
      - completed

jobs:
  upload:
    if: false  # Disabled - benchmarking not functional
    runs-on: ubuntu-latest
    steps:
      - uses: seabbs/touchstone/actions/comment@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
